import './global.css';

import { cn } from '@parse-ranking/shadcn-ui';
import { Inter as FontSans } from 'next/font/google';

import { Header } from '../src/components/header';
import { ThemeProvider } from '../src/components/theme-provider';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata = {
  title: 'Welcome to parse-ranking-front-end',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <ThemeProvider attribute="class" disableTransitionOnChange>
          <Header />
          <main className="flex justify-center mx-6 my-4">
            <div className="max-w-2xl flex-1">{children}</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
