services:
  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: parse-ranking
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    ports:
      - 8080:8080
